#!/bin/sh
#
# This script will build all the roady Apps the
# are currently installed in roady's Apps directory.
#
# Usage
#
# buildAllApps
#

msg() {
    printf '%b%s%b' "\n\n\e[0m\e[105m\e[30m" "$1" "\e[0m\n\n"
}

msgAndExit() {
    msg "$1"
    exit 1
}

pathToPhpProjects="$HOME/dev/php"
pathToRoady="$pathToPhpProjects/roady"
pathToRoadyApps="$pathToRoady/Apps"
availableApps="$pathToRoadyApps/*"

[ ! -d "$pathToRoady" ] &&
    msgAndExit "roady is not installed."

[ ! -d "$pathToRoadyApps" ] &&
    msgAndExit "roady's Apps directory does not exist."

for app in  $availableApps
do
    pathToAppsComponentsPhp="$app/Components.php"
    [ -f "$pathToAppsComponentsPhp" ] &&
        php "$pathToAppsComponentsPhp" &&
        msg "Finished building the $app App"
done

