#!/bin/sh

# Functions

msg() {
    printf '\n\n\e[0m\e[105m\e[30m%s\e[0m\n\n' "$1"
}

msgAndExit() {
    msg "$1"
    exit 1
}

# Variables

pathToPhpProjects="$HOME/dev/php"
pathToRoady="$pathToPhpProjects/roady"
pathToRoadyApps="$pathToRoady/Apps"
availableApps="$pathToRoadyApps/*"

[ ! -d "$pathToRoady" ] &&
    msgAndExit "roady is not installed."

[ ! -d "$pathToRoadyApps" ] &&
    msgAndExit "roady's Apps directory does not exist."

for app in  $availableApps
do
    [ -f "$app/Components.php" ] &&
        /usr/bin/php "$app/Components.php" &&
        msg "Finished building the $app App"
done


