#!/bin/sh

# LICENSE
#
# MIT License
#
# Copyright (c) 2023 Sevi Donnelly Foreman
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
# https://github.com/sevidmusic/
#

# Functions

msg() {
    printf "\n%b%b%b%s%b\n\n" "\e[0m" "\e[105m" "\e[30m" "$1" "\e[0m"
}

msgAndExit() {
    msg "$1" && exit "$2"
}

# Variables

itemToDelete="$1"

# Logic

[ "$itemToDelete" = '/' ] &&
    msgAndExit 'WARNING: You cannot delete /' 1

[ "$itemToDelete" = "$HOME" ] &&
    msgAndExit "WARNING: You cannot delete $HOME" 1

[ "$itemToDelete" = ~/ ] &&
    msgAndExit "WARNING: You cannot delete $HOME" 1

[ "$itemToDelete" = ./ ] &&
    msgAndExit "WARNING: You cannot delete the current working directory" 1

[ ! -d "$itemToDelete" ] &&
    [ ! -f "$itemToDelete" ] &&
    msgAndExit "$itemToDelete does not exist" 1


msg "Are you sure you want to delete $itemToDelete?"
msg '(enter "Y" to confirm, or any other key to cancel)'
read -r performDeletion

[ ! "$performDeletion" = 'Y' ] &&
    msgAndExit "$itemToDelete was not deleted." 0

[ "$performDeletion" = 'Y' ] &&
    [ -f "$itemToDelete" ] &&
    shred -n17 --remove "$itemToDelete" &&
    msgAndExit "Deleted file: $itemToDelete" 0

[ "$performDeletion" = 'Y' ] &&
    rm -Rf "$itemToDelete" &&
    msgAndExit "Deleted directory: $itemToDelete" 0
