#!/bin/sh
#
# This script will install phpTextTypes and create
# and push a new development branch.
#
# Usage
#
# installPHPJsonUtilities
#

msg() {
    printf '%b%s%b' "\n\n\e[0m\e[105m\e[30m" "$1" "\e[0m\n\n"
}

msgAndExit() {
    msg "$1"
    exit 1
}

timestamp=$(/usr/bin/date +"%s")
pathToGitProjects="$HOME/Git"
pathToPHPJsonUtilities="$pathToGitProjects/PHPJsonUtilities"
pass=$(/usr/bin/pass sevidmusic.github.roadybetadev.key)
newBranchName="PHPJsonUtilities$timestamp"
pathToPhpUnit="$pathToPHPJsonUtilities/vendor/bin/phpunit"
pathToPhpStan="$pathToPHPJsonUtilities/vendor/bin/phpstan"
pathToComposer="/home/darling/.local/bin/composer"

[ -d "$pathToPHPJsonUtilities" ] && msgAndExit 'PHPJsonUtilities is already installed.'

[ ! -d "$pathToGitProjects" ] && mkdir -p "$pathToGitProjects"

cd "$pathToGitProjects" ||
    msgAndExit "Failed to move into $pathToGitProjects"

git clone "https://sevidmusic:$pass@github.com/sevidmusic/PHPJsonUtilities.git"

cd "$pathToPHPJsonUtilities" ||
    msgAndExit "Failed to move into $pathToPHPJsonUtilities"

"$pathToComposer" update ||
    msgAndExit 'Failed to run composer update'

"$pathToPhpUnit" -c "$pathToPHPJsonUtilities/php.xml"

"$pathToPhpStan" analyze --level 9 \
    "$pathToPHPJsonUtilities/src" \
    "$pathToPHPJsonUtilities/tests"

git checkout -b "$newBranchName"
git push --set-upstream origin "$newBranchName"

msg "Installed PHPJsonUtilities at $pathToPHPJsonUtilities"
msg "Ran phpunit tests"
msg "Ran phpstan tests"

