#!/bin/sh
#
# This script will install RoadyRoutes and create
# and push a new development branch.
#
# Usage
#
# installRoadyRoutes
#

msg() {
    printf '%b%s%b' "\n\n\e[0m\e[105m\e[30m" "$1" "\e[0m\n\n"
}

msgAndExit() {
    msg "$1"
    exit 1
}

timestamp=$(/usr/bin/date +"%s")
pathToGitProjects="$HOME/Git"
pathToRoadyRoutes="$pathToGitProjects/RoadyRoutes"
pass=$(/usr/bin/pass sevidmusic.github.Roadybetadev.key)
newBranchName="RoadyRoutes$timestamp"
pathToPhpUnit="$pathToRoadyRoutes/vendor/bin/phpunit"
pathToPhpStan="$pathToRoadyRoutes/vendor/bin/phpstan"
pathToComposer="/home/darling/.local/bin/composer"

[ -d "$pathToRoadyRoutes" ] && msgAndExit 'RoadyRoutes is already installed.'

[ ! -d "$pathToGitProjects" ] && mkdir -p "$pathToGitProjects"

cd "$pathToGitProjects" ||
    msgAndExit "Failed to move into $pathToGitProjects"

git clone "https://sevidmusic:$pass@github.com/sevidmusic/RoadyRoutes.git"

cd "$pathToRoadyRoutes" ||
    msgAndExit "Failed to move into $pathToRoadyRoutes"

"$pathToComposer" update ||
    msgAndExit 'Failed to run composer update'

"$pathToPhpUnit" -c "$pathToRoadyRoutes/php.xml"

"$pathToPhpStan" analyze --level 9 \
    "$pathToRoadyRoutes/src" \
    "$pathToRoadyRoutes/tests"

git checkout -b "$newBranchName"
git push --set-upstream origin "$newBranchName"

msg "Installed RoadyRoutes at $pathToRoadyRoutes"
msg "Ran phpunit tests"
msg "Ran phpstan tests"

