#!/bin/sh
#
# This script will install roadyAppPackages, and create
# and push a new development branch.
#
# Usage:
#
# installRoadyAppPackages
#

msg() {
    printf '%b%s%b' "\n\n\e[0m\e[105m\e[30m" "$1" "\e[0m\n\n"
}

msgAndExit() {
    msg "$1"
    exit 1
}

timestamp=$(/usr/bin/date +"%s")
pathToPhpProjects="$HOME/dev/php"
pathToRoadyAppPackages="$pathToPhpProjects/roadyAppPackages"
pass=$(/usr/bin/pass sevidmusic.github.roadybetadev.key)
newBranchName="roadyAppPackages$timestamp"

[ -d "$pathToRoadyAppPackages" ] &&
    msgAndExit 'The roadyAppPackages library is already installed.'

[ ! -d "$pathToPhpProjects" ] &&
    mkdir -p "$pathToPhpProjects"

cd "$pathToPhpProjects" ||
    msgAndExit "Failed to move into $pathToPhpProjects"

git clone "https://sevidmusic:$pass@github.com/sevidmusic/roadyAppPackages.git"

cd "$pathToRoadyAppPackages" ||
    msgAndExit "Failed to move into $pathToRoadyAppPackages"

git checkout -b "$newBranchName"
git push --set-upstream origin "$newBranchName"

msg "Installed roadyAppPackages at $pathToRoadyAppPackages"

