#!/bin/sh
#
# This script will install phpTextTypes and create
# and push a new development branch.
#
# Usage
#
# installPHPJsonStorageUtilities
#

msg() {
    printf '%b%s%b' "\n\n\e[0m\e[105m\e[30m" "$1" "\e[0m\n\n"
}

msgAndExit() {
    msg "$1"
    exit 1
}

timestamp=$(/usr/bin/date +"%s")
pathToGitProjects="$HOME/Git"
pathToPHPJsonStorageUtilities="$pathToGitProjects/PHPJsonStorageUtilities"
pass=$(/usr/bin/pass sevidmusic.github.roadybetadev.key)
newBranchName="PHPJsonStorageUtilities$timestamp"
pathToPhpUnit="$pathToPHPJsonStorageUtilities/vendor/bin/phpunit"
pathToPhpStan="$pathToPHPJsonStorageUtilities/vendor/bin/phpstan"
pathToComposer="/home/darling/.local/bin/composer"

[ -d "$pathToPHPJsonStorageUtilities" ] && msgAndExit 'PHPJsonStorageUtilities is already installed.'

[ ! -d "$pathToGitProjects" ] && mkdir -p "$pathToGitProjects"

cd "$pathToGitProjects" ||
    msgAndExit "Failed to move into $pathToGitProjects"

git clone "https://sevidmusic:$pass@github.com/sevidmusic/PHPJsonStorageUtilities.git"

cd "$pathToPHPJsonStorageUtilities" ||
    msgAndExit "Failed to move into $pathToPHPJsonStorageUtilities"

"$pathToComposer" update ||
    msgAndExit 'Failed to run composer update'

"$pathToPhpUnit" -c "$pathToPHPJsonStorageUtilities/php.xml"

"$pathToPhpStan" analyze --level 9 \
    "$pathToPHPJsonStorageUtilities/src" \
    "$pathToPHPJsonStorageUtilities/tests"

"$pathToPHPJsonStorageUtilities/runIntegrationTests.sh"

printf '%b' "\e[0m\n"

git checkout -b "$newBranchName"
git push --set-upstream origin "$newBranchName"

msg "Installed PHPJsonStorageUtilities at $pathToPHPJsonStorageUtilities"
msg "Ran phpunit tests"
msg "Ran phpstan tests"

