#!/bin/sh
#
# This script will install RoadyUIUtilities and create
# and push a new development branch.
#
# Usage
#
# installRoadyUIUtilities
#

msg() {
	printf '%b%s%b' "\n\n\e[0m\e[105m\e[30m" "$1" "\e[0m\n\n"
}

msgAndExit() {
	msg "$1"
	exit 1
}

timestamp=$(/usr/bin/date +"%s")
pathToGitProjects="$HOME/Git"
pathToRoadyUIUtilities="$pathToGitProjects/RoadyUIUtilities"
pass=$(/usr/bin/pass sevidmusic.github.roadybetadev.key)
newBranchName="RoadyUIUtilities$timestamp"
pathToPhpUnit="$pathToRoadyUIUtilities/vendor/bin/phpunit"
pathToPhpStan="$pathToRoadyUIUtilities/vendor/bin/phpstan"
pathToComposer="/home/darling/.local/bin/composer"

[ -d "$pathToRoadyUIUtilities" ] && msgAndExit 'RoadyUIUtilities is already installed.'

[ ! -d "$pathToGitProjects" ] && mkdir -p "$pathToGitProjects"

cd "$pathToGitProjects" ||
	msgAndExit "Failed to move into $pathToGitProjects"

git clone "https://sevidmusic:$pass@github.com/sevidmusic/RoadyUIUtilities.git"

cd "$pathToRoadyUIUtilities" ||
	msgAndExit "Failed to move into $pathToRoadyUIUtilities"

"$pathToComposer" update ||
	msgAndExit 'Failed to run composer update'

"$pathToPhpUnit" -c "$pathToRoadyUIUtilities/php.xml"

"$pathToPhpStan" analyze --level 9 \
	"$pathToRoadyUIUtilities/src" \
	"$pathToRoadyUIUtilities/tests"

git checkout -b "$newBranchName"
git push --set-upstream origin "$newBranchName"

msg "Installed RoadyUIUtilities at $pathToRoadyUIUtilities"
msg "Ran phpunit tests"
msg "Ran phpstan tests"
