#!/bin/sh
#
# This script will install phpTextTypes and create
# and push a new development branch.
#
# Usage
#
# installPHPDarlingDevTools
#

msg() {
    printf '%b%s%b' "\n\n\e[0m\e[105m\e[30m" "$1" "\e[0m\n\n"
}

msgAndExit() {
    msg "$1"
    exit 1
}

timestamp=$(/usr/bin/date +"%s")
pathToGitProjects="$HOME/Git"
pathToPHPDarlingDevTools="$pathToGitProjects/PHPDarlingDevTools"
pass=$(/usr/bin/pass sevidmusic.github.roadybetadev.key)
newBranchName="PHPDarlingDevTools$timestamp"
pathToPhpStan="$pathToPHPDarlingDevTools/vendor/bin/phpstan"
pathToComposer="/home/darling/.local/bin/composer"

[ -d "$pathToPHPDarlingDevTools" ] && msgAndExit 'PHPDarlingDevTools is already installed.'

[ ! -d "$pathToGitProjects" ] && mkdir -p "$pathToGitProjects"

cd "$pathToGitProjects" ||
    msgAndExit "Failed to move into $pathToGitProjects"

git clone "https://sevidmusic:$pass@github.com/sevidmusic/PHPDarlingDevTools.git"

cd "$pathToPHPDarlingDevTools" ||
    msgAndExit "Failed to move into $pathToPHPDarlingDevTools"

"$pathToComposer" update ||
    msgAndExit 'Failed to run composer update'

"$pathToPhpStan" analyze --level 9 \
    "$pathToPHPDarlingDevTools/src" \
    "$pathToPHPDarlingDevTools/tests"

git checkout -b "$newBranchName"
git push --set-upstream origin "$newBranchName"

msg "Installed PHPDarlingDevTools at $pathToPHPDarlingDevTools"

