#!/bin/sh
#
# This script will install roady and create
# and push a new development branch.
#
# Usage
#
# installRoady
#

msg() {
    printf '%b%s%b' "\n\n\e[0m\e[105m\e[30m" "$1" "\e[0m\n\n"
}

msgAndExit() {
    msg "$1"
    exit 1
}

timestamp=$(/usr/bin/date +"%s")
pathToPhpProjects="$HOME/Git"
pathToRoady="$pathToPhpProjects/roady"
pass=$(/usr/bin/pass sevidmusic.github.roadybetadev.key)
newBranchName="roady$timestamp"
pathToPhpUnit="$pathToRoady/vendor/bin/phpunit"
pathToPhpStan="$pathToRoady/vendor/bin/phpstan"
pathToComposer="/home/darling/.local/bin/composer"

[ -d "$pathToRoady" ] && msgAndExit 'Roady is already installed.'

[ ! -d "$pathToPhpProjects" ] && mkdir -p "$pathToPhpProjects"

cd "$pathToPhpProjects" ||
    msgAndExit "Failed to move into $pathToPhpProjects"

git clone "https://sevidmusic:$pass@github.com/sevidmusic/roady.git"

cd "$pathToRoady" ||
    msgAndExit "Failed to move into $pathToRoady"

"$pathToComposer" update ||
    msgAndExit 'Failed to run composerupdate'

"$pathToPhpUnit" -c "$pathToRoady/php.xml"

"$pathToPhpStan" analyze --level 9 \
    "$pathToRoady/src" \
    "$pathToRoady/tests"

git checkout -b "$newBranchName"
git push --set-upstream origin "$newBranchName"

msg "Installed roady at $pathToRoady"
msg "Ran phpunit tests"
msg "Ran phpstan tests"

