#!/bin/sh
#
# This script will install phpTextTypes and create
# and push a new development branch.
#
# Usage
#
# installPHPTextTypes
#

msg() {
    printf '%b%s%b' "\n\n\e[0m\e[105m\e[30m" "$1" "\e[0m\n\n"
}

msgAndExit() {
    msg "$1"
    exit 1
}

timestamp=$(/usr/bin/date +"%s")
pathToGitProjects="$HOME/Git"
pathToPHPTextTypes="$pathToGitProjects/PHPTextTypes"
pass=$(/usr/bin/pass sevidmusic.github.roadybetadev.key)
newBranchName="PHPTextTypes$timestamp"
pathToPhpUnit="$pathToPHPTextTypes/vendor/bin/phpunit"
pathToPhpStan="$pathToPHPTextTypes/vendor/bin/phpstan"
pathToComposer="/home/darling/.local/bin/composer"

[ -d "$pathToPHPTextTypes" ] && msgAndExit 'PHPTextTypes is already installed.'

[ ! -d "$pathToGitProjects" ] && mkdir -p "$pathToGitProjects"

cd "$pathToGitProjects" ||
    msgAndExit "Failed to move into $pathToGitProjects"

git clone "https://sevidmusic:$pass@github.com/sevidmusic/PHPTextTypes.git"

cd "$pathToPHPTextTypes" ||
    msgAndExit "Failed to move into $pathToPHPTextTypes"

"$pathToComposer" update ||
    msgAndExit 'Failed to run composer update'

"$pathToPhpUnit" -c "$pathToPHPTextTypes/php.xml"

"$pathToPhpStan" analyze --level 9 \
    "$pathToPHPTextTypes/src" \
    "$pathToPHPTextTypes/tests"

git checkout -b "$newBranchName"
git push --set-upstream origin "$newBranchName"

msg "Installed PHPTextTypes at $pathToPHPTextTypes"
msg "Ran phpunit tests"
msg "Ran phpstan tests"

