#!/bin/sh
#
# This script will install phpTextTypes and create
# and push a new development branch.
#
# Usage
#
# installPHPMockingUtilities
#

msg() {
    printf '%b%s%b' "\n\n\e[0m\e[105m\e[30m" "$1" "\e[0m\n\n"
}

msgAndExit() {
    msg "$1"
    exit 1
}

timestamp=$(/usr/bin/date +"%s")
pathToGitProjects="$HOME/Git"
pathToPHPMockingUtilities="$pathToGitProjects/PHPMockingUtilities"
pass=$(/usr/bin/pass sevidmusic.github.roadybetadev.key)
newBranchName="PHPMockingUtilities$timestamp"
pathToPhpUnit="$pathToPHPMockingUtilities/vendor/bin/phpunit"
pathToPhpStan="$pathToPHPMockingUtilities/vendor/bin/phpstan"
pathToComposer="/home/darling/.local/bin/composer"

[ -d "$pathToPHPMockingUtilities" ] && msgAndExit 'PHPMockingUtilities is already installed.'

[ ! -d "$pathToGitProjects" ] && mkdir -p "$pathToGitProjects"

cd "$pathToGitProjects" ||
    msgAndExit "Failed to move into $pathToGitProjects"

git clone "https://sevidmusic:$pass@github.com/sevidmusic/PHPMockingUtilities.git"

cd "$pathToPHPMockingUtilities" ||
    msgAndExit "Failed to move into $pathToPHPMockingUtilities"

"$pathToComposer" update ||
    msgAndExit 'Failed to run composer update'

"$pathToPhpUnit" -c "$pathToPHPMockingUtilities/php.xml"

"$pathToPhpStan" analyze --level 9 \
    "$pathToPHPMockingUtilities/src" \
    "$pathToPHPMockingUtilities/tests"

git checkout -b "$newBranchName"
git push --set-upstream origin "$newBranchName"

msg "Installed PHPMockingUtilities at $pathToPHPMockingUtilities"
msg "Ran phpunit tests"
msg "Ran phpstan tests"

