#!/bin/sh
#
# This script will install PHPFileSystemPaths and create
# and push a new development branch.
#
# Usage
#
# installPHPFileSystemPaths
#

msg() {
    printf '%b%s%b' "\n\n\e[0m\e[105m\e[30m" "$1" "\e[0m\n\n"
}

msgAndExit() {
    msg "$1"
    exit 1
}

timestamp=$(/usr/bin/date +"%s")
pathToGitProjects="$HOME/Git"
pathToPHPFileSystemPaths="$pathToGitProjects/PHPFileSystemPaths"
pass=$(/usr/bin/pass sevidmusic.github.roadybetadev.key)
newBranchName="PHPFileSystemPaths$timestamp"
pathToPhpUnit="$pathToPHPFileSystemPaths/vendor/bin/phpunit"
pathToPhpStan="$pathToPHPFileSystemPaths/vendor/bin/phpstan"
pathToComposer="/home/darling/.local/bin/composer"

[ -d "$pathToPHPFileSystemPaths" ] && msgAndExit 'PHPFileSystemPaths is already installed.'

[ ! -d "$pathToGitProjects" ] && mkdir -p "$pathToGitProjects"

cd "$pathToGitProjects" ||
    msgAndExit "Failed to move into $pathToGitProjects"

git clone "https://sevidmusic:$pass@github.com/sevidmusic/PHPFileSystemPaths.git"

cd "$pathToPHPFileSystemPaths" ||
    msgAndExit "Failed to move into $pathToPHPFileSystemPaths"

"$pathToComposer" update ||
    msgAndExit 'Failed to run composer update'

"$pathToPhpUnit" -c "$pathToPHPFileSystemPaths/php.xml"

"$pathToPhpStan" analyze --level 9 \
    "$pathToPHPFileSystemPaths/src" \
    "$pathToPHPFileSystemPaths/tests"

git checkout -b "$newBranchName"
git push --set-upstream origin "$newBranchName"

msg "Installed PHPFileSystemPaths at $pathToPHPFileSystemPaths"
msg "Ran phpunit tests"
msg "Ran phpstan tests"

