#!/bin/sh

# Functions

msg() {
    printf '\n\n\e[0m\e[105m\e[30m%s\e[0m\n\n' "$1"
}

msgAndExit() {
    msg "$1"
    exit 1
}

# Variables

pathToPhpProjects="$HOME/dev/php"
pathToRoady="$pathToPhpProjects/roady"
pass=$(/usr/bin/pass sevidmusic.github.roadybetadev.key)


[ -d "$pathToRoady" ] && msgAndExit 'Roady is already installed.'

[ ! -d "$pathToPhpProjects" ] && mkdir -p "$pathToPhpProjects"

cd "$pathToPhpProjects" || msgAndExit "Failed to move into $pathToPhpProjects"

/usr/bin/git clone "https://sevidmusic:$pass@github.com/sevidmusic/roady.git"

cd "$pathToRoady" || msgAndExit "Failed to move into $pathToRoady"

/home/darling/.local/bin/composer update || msgAndExit 'Failed to run composerupdate'

"$pathToRoady/vendor/bin/phpunit" -c "$pathToRoady/php.xml"

"$pathToRoady/vendor/bin/phpstan" analyze --level 8 "$pathToRoady/index.php" "$pathToRoady/Tests" "$pathToRoady/core"

[ ! -L "$HOME/.darling/rig" ] && ln -s "$HOME/dev/php/roady/vendor/darling/rig/bin/rig" "$HOME/.darling/rig"

[ ! -L "$HOME/.darling/rig" ] && msgAndExit 'Failed to create a symlink to rig.'

msg "Installed roady at $pathToRoady | ran phpunit tests | ran phpstan tests | created symlink to rig in $HOME/.darling"

