#!/bin/sh
#
# This script will install phpReflectionUtilities and create
# and push a new development branch.
#
# Usage
#
# installPHPReflectionUtilities
#

msg() {
    printf '%b%s%b' "\n\n\e[0m\e[105m\e[30m" "$1" "\e[0m\n\n"
}

msgAndExit() {
    msg "$1"
    exit 1
}

timestamp=$(/usr/bin/date +"%s")
pathToGitProjects="$HOME/Git"
pathToPHPReflectionUtilities="$pathToGitProjects/PHPReflectionUtilities"
pass=$(/usr/bin/pass sevidmusic.github.roadybetadev.key)
newBranchName="PHPReflectionUtilities$timestamp"
pathToPhpUnit="$pathToPHPReflectionUtilities/vendor/bin/phpunit"
pathToPhpStan="$pathToPHPReflectionUtilities/vendor/bin/phpstan"
pathToComposer="/home/darling/.local/bin/composer"

[ -d "$pathToPHPReflectionUtilities" ] && msgAndExit 'PHPReflectionUtilities is already installed.'

[ ! -d "$pathToGitProjects" ] && mkdir -p "$pathToGitProjects"

cd "$pathToGitProjects" ||
    msgAndExit "Failed to move into $pathToGitProjects"

git clone "https://sevidmusic:$pass@github.com/sevidmusic/PHPReflectionUtilities.git"

cd "$pathToPHPReflectionUtilities" ||
    msgAndExit "Failed to move into $pathToPHPReflectionUtilities"

"$pathToComposer" update ||
    msgAndExit 'Failed to run composerupdate'

"$pathToPhpUnit" -c "$pathToPHPReflectionUtilities/php.xml"

"$pathToPhpStan" analyze --level 9 \
    "$pathToPHPReflectionUtilities/src" \
    "$pathToPHPReflectionUtilities/tests"

git checkout -b "$newBranchName"
git push --set-upstream origin "$newBranchName"

msg "Installed PHPReflectionUtilities at $pathToPHPReflectionUtilities"
msg "Ran phpunit tests"
msg "Ran phpstan tests"

