#!/bin/sh
#
# This script will install RoadyModuleUtilities and create
# and push a new development branch.
#
# Usage
#
# installRoadyModuleUtilities
#

msg() {
    printf '%b%s%b' "\n\n\e[0m\e[105m\e[30m" "$1" "\e[0m\n\n"
}

msgAndExit() {
    msg "$1"
    exit 1
}

timestamp=$(/usr/bin/date +"%s")
pathToGitProjects="$HOME/Git"
pathToRoadyModuleUtilities="$pathToGitProjects/RoadyModuleUtilities"
pass=$(/usr/bin/pass sevidmusic.github.roadybetadev.key)
newBranchName="RoadyModuleUtilities$timestamp"
pathToPhpUnit="$pathToRoadyModuleUtilities/vendor/bin/phpunit"
pathToPhpStan="$pathToRoadyModuleUtilities/vendor/bin/phpstan"
pathToComposer="/home/darling/.local/bin/composer"

[ -d "$pathToRoadyModuleUtilities" ] && msgAndExit 'RoadyModuleUtilities is already installed.'

[ ! -d "$pathToGitProjects" ] && mkdir -p "$pathToGitProjects"

cd "$pathToGitProjects" ||
    msgAndExit "Failed to move into $pathToGitProjects"

git clone "https://sevidmusic:$pass@github.com/sevidmusic/RoadyModuleUtilities.git"

cd "$pathToRoadyModuleUtilities" ||
    msgAndExit "Failed to move into $pathToRoadyModuleUtilities"

"$pathToComposer" update ||
    msgAndExit 'Failed to run composer update'

"$pathToPhpUnit" -c "$pathToRoadyModuleUtilities/php.xml"

"$pathToPhpStan" analyze --level 9 \
    "$pathToRoadyModuleUtilities/src" \
    "$pathToRoadyModuleUtilities/tests"

git checkout -b "$newBranchName"
git push --set-upstream origin "$newBranchName"

msg "Installed RoadyModuleUtilities at $pathToRoadyModuleUtilities"
msg "Ran phpunit tests"
msg "Ran phpstan tests"

