#!/bin/sh
#
# This script randomly change the color scheme using pywal
# every 17 seconds to match a randomly selected picture
# from ~/Pictures.
#
# Usage:
#
# loopWal
#

wal -c

while :
do
    wal --backend colorthief -q -i ~/Pictures/
    sleep 17
done

