#!/bin/bash
#
# NOTE: `bash` is used instead of `sh` on purpose in this script.
#
# This script randomly change the color scheme using pywal
# every 17 seconds to match a randomly selected picture
# from ~/Pictures using a randomly selected color backend.
#
# Usage:
#
# loopWal
#

msg() {
    printf '%b%s%b' "\n\n\e[0m\e[105m\e[30m" "$1" "\e[0m\n\n"
}

msgAndExit() {
    msg "$1"
    exit 1
}

colorBackends=("wal" "colorz" "colorthief")
waitTime="${1:-10}"
show="${2:-show}"

while :
do
    # Uncomment to use a random color backend
    colorBackend=${colorBackends[ $RANDOM % ${#colorBackends[@]} ]}

    # Uncomment to use a specific color backend
    #colorBackend="colorthief"

    # Select a random image from ~/Pictures
    randomImage=$(find ~/Pictures/ -type f | sort -R | tail -1)

    # Save backend to file so last backend used can be determined
    echo "$colorBackend" > ~/.lastColorBackend.txt

    changeColors "$randomImage" "$colorBackend"
    [ "$show" == 'show' ] &&
        clear &&
        msg "loopwal is running (use ctrl-c to exit)" &&
        msg "Image: $randomImage | Backend: $colorBackend"

    sleep "$waitTime"
done

