#!/bin/bash

colorBackends=("wal" "colorz" "colorthief")

colorBackend=${colorBackends[ $RANDOM % ${#colorBackends[@]} ]}

randomImage=$(find ~/Pictures/ -type f | sort -R | tail -1)

changeColors "${randomImage}" "${colorBackend}"

