#!/bin/sh

msg() {
    printf '%b%s%b' "\n\n\e[0m\e[105m\e[30m" "$1" "\e[0m\n\n"
}

msgAndExit() {
    msg "$1"
    exit 1
}

[ ! -d ./.git ] &&
    msgAndExit "Please move into a development directory to start recording"

timestamp=$(/usr/bin/date +"%s")
branchName="$(git status | grep 'origin' | awk 'BEGIN { FS = "/" }; {print $2}' | sed "s/'.//g")"

asciinema rec "${HOME}/Videos/asciinema/${timestamp}_${branchName}.cast"
