#!/bin/bash

# Define the table as an array of arrays.
table=(
    '. Matches any single character except newline.'
    '^ Matches the start of the string.'
    '$ Matches the end of the string.'
    '* Matches 0 or more occurrences of the preceding character.'
    '+ Matches 1 or more occurrences of the preceding character.'
    '? Matches 0 or 1 occurrence of the preceding character.'
    '{m} Matches exactly m occurrences of the preceding character.'
    '{m,} Matches m or more occurrences of the preceding character.'
    '{m,n} Matches between m and n occurrences of the preceding character.'
    '[] Matches any character inside the square brackets.'
    '| Matches either the expression before or after the |.'
    '() Groups expressions together.'
    '\\ Escapes special characters.'
)

tput setab 0
tput setaf 202
figlet -f pagga "Regex Cheat Sheet"
tput setaf 207
# Print the table.
for key in "${!table[@]}"; do
    printf " %s \n" "${table[$key]}"
done
tput sgr0

