#!/bin/sh
#
# This script will remove the $HOME/dev directory,
# which may contain the development versions of
# roady, rig, and roadyAppPackages
#
# Usage:
#
# removeDevDirectory
#

pathToDev="$HOME/dev"
printf "%bAre you sure that you want to delete the %s directory, which includes the current development version of roady? (y|n)%b" "\n\e[0m\e[105m\e[30m" "$pathToDev" "\e[0m\n";
read -r c; [ "$c" = "y" ] &&
    [ -d "$pathToDev" ] &&
    rm -Rf "$pathToDev"

