#!/bin/sh
#
# This script will do the following:
# 1. Remove roady's .StoredComponentJsonData
# 2. Remove roady's App build logs
# 3. Clear php's error log
#
# Usage:
#
# roadyDevClean
#

msg() {
    printf '%b%s%b' "\n\n\e[0m\e[105m\e[30m" "$1" "\e[0m\n\n"
}

msgAndExit() {
    msg "$1"
    exit 1
}

pathToPhpProjects="$HOME/dev/php"
pathToRoady="$pathToPhpProjects/roady"
pathToRoadyStorage="$pathToRoady/.StoredComponentJsonData"
pathToRoadyAppBuildLogs="$pathToRoady/Apps/.buildLogs"
pathToPhpsErrorLog="$HOME/logs/php/local_php_errors.log"

[ -d "$pathToRoadyStorage" ] &&
    rm -Rf "$pathToRoadyStorage" &&
    msg "Removed $pathToRoadyStorage"

[ -d "$pathToRoadyAppBuildLogs" ] &&
    rm -Rf "$pathToRoadyAppBuildLogs" &&
    msg "Removed $pathToRoadyAppBuildLogs"

[ -f "$pathToPhpsErrorLog" ] &&
    echo '' > "$pathToPhpsErrorLog" &&
    msg "Cleared log: $pathToPhpsErrorLog"

