#!/bin/sh
#
# This script will run `phpstan` tests via `entr` whenever
# a file in PHPJsonStorageUtilities's src/ or Tests/ directory
# is modified.
#
# Usage:
#
# runPHPStanTestsOnSavePHPUnitTestUtilties
#

msg() {
    printf '%b%s%b' "\n\n\e[0m\e[105m\e[30m" "$1" "\e[0m\n\n"
}

msgAndExit() {
    msg "$1"
    exit 1
}

pathToPHPProjects="$HOME/Git"
pathToPHPJsonStorageUtilities="$pathToPHPProjects/PHPJsonStorageUtilities"
pathToPHPStan="$pathToPHPJsonStorageUtilities/vendor/bin/phpstan"

cd "$pathToPHPJsonStorageUtilities" || msgAndExit 'PHPJsonStorageUtilities is not installed'

find \
    "$pathToPHPJsonStorageUtilities/tests" \
    "$pathToPHPJsonStorageUtilities/src" \
    "$pathToPHPJsonStorageUtilities/examples" \
    -type f -name "*.php" |
    entr -c "$pathToPHPStan"

