#!/bin/sh
#
# This script will run `phpstan` tests via `entr` whenever
# a file in PHPMockingUtilities's src/ or Tests/ directory
# is modified.
#
# Usage:
#
# runPHPStanTestsOnSavePHPUnitTestUtilties
#

msg() {
    printf '%b%s%b' "\n\n\e[0m\e[105m\e[30m" "$1" "\e[0m\n\n"
}

msgAndExit() {
    msg "$1"
    exit 1
}

pathToPHPProjects="$HOME/Git"
pathToPHPMockingUtilities="$pathToPHPProjects/PHPMockingUtilities"
pathToPHPStan="$pathToPHPMockingUtilities/vendor/bin/phpstan"

cd "$pathToPHPMockingUtilities" || msgAndExit 'PHPMockingUtilities is not installed'

find \
    "$pathToPHPMockingUtilities/tests" \
    "$pathToPHPMockingUtilities/src" \
    -type f -name "*.php" |
    entr -c "$pathToPHPStan"

