#!/bin/sh
#
# This script will run `phpunit` tests via `entr` whenever
# a file in either PHPJsonStorageUtilities's src/ or tests/
# directoy is modified.
#
# Usage:
#
# runPHPUnitTestsOnSavePHPJsonStorageUtilities
#

msg() {
    printf '%b%s%b' "\n\n\e[0m\e[105m\e[30m" "$1" "\e[0m\n\n"
}

msgAndExit() {
    msg "$1"
    exit 1
}

pathToPhpProjects="$HOME/Git"
pathToPHPJsonStorageUtilities="$pathToPhpProjects/PHPJsonStorageUtilities"
pathToPhpUnit="$pathToPHPJsonStorageUtilities/vendor/bin/phpunit"

cd "$pathToPHPJsonStorageUtilities" || msgAndExit 'PHPJsonStorageUtilities is not installed'

find \
    "$pathToPHPJsonStorageUtilities/tests" \
    "$pathToPHPJsonStorageUtilities/src" \
    -type f -name "*.php" |
    entr -c "$pathToPhpUnit" -c "$pathToPHPJsonStorageUtilities/php.xml"

