#!/bin/sh
#
# This script will run `phpunit` tests via `entr` whenever
# a file in either PHPJsonUtilities's src/ or tests/
# directoy is modified.
#
# Usage:
#
# runPHPUnitTestsOnSavePHPJsonUtilities
#

msg() {
    printf '%b%s%b' "\n\n\e[0m\e[105m\e[30m" "$1" "\e[0m\n\n"
}

msgAndExit() {
    msg "$1"
    exit 1
}

pathToPhpProjects="$HOME/Git"
pathToPHPJsonUtilities="$pathToPhpProjects/PHPJsonUtilities"
pathToPhpUnit="$pathToPHPJsonUtilities/vendor/bin/phpunit"

cd "$pathToPHPJsonUtilities" || msgAndExit 'PHPJsonUtilities is not installed'

find \
    "$pathToPHPJsonUtilities/tests" \
    "$pathToPHPJsonUtilities/src" \
    -type f -name "*.php" |
    entr -c "$pathToPhpUnit" -c "$pathToPHPJsonUtilities/php.xml"

