#!/bin/sh
#
# This script will run `phpunit` tests via `entr` whenever
# a file in either RoadyRoutingUtilities's src/ or tests/
# directoy is modified.
#
# Usage:
#
# runPHPUnitTestsOnSaveRoadyRoutingUtilities
#

msg() {
	printf '%b%s%b' "\n\n\e[0m\e[105m\e[30m" "$1" "\e[0m\n\n"
}

msgAndExit() {
	msg "$1"
	exit 1
}

pathToPhpProjects="$HOME/Git"
pathToRoadyRoutingUtilities="$pathToPhpProjects/RoadyRoutingUtilities"
pathToPhpUnit="$pathToRoadyRoutingUtilities/vendor/bin/phpunit"

cd "$pathToRoadyRoutingUtilities" || msgAndExit 'RoadyRoutingUtilities is not installed'

find \
	"$pathToRoadyRoutingUtilities/tests" \
	"$pathToRoadyRoutingUtilities/src" \
	-type f -name "*.php" |
	entr -c "$pathToPhpUnit" -c "$pathToRoadyRoutingUtilities/php.xml"
