#!/bin/sh
#
# This script will run `phpunit` tests via `entr` whenever
# a file in either PHPReflectionUtilities's src/ or tests/
# directoy is modified.
#
# Usage:
#
# runPHPUnitTestsOnSavePHPReflectionUtilities
#

msg() {
    printf '%b%s%b' "\n\n\e[0m\e[105m\e[30m" "$1" "\e[0m\n\n"
}

msgAndExit() {
    msg "$1"
    exit 1
}

pathToPhpProjects="$HOME/Git"
pathToPHPReflectionUtilities="$pathToPhpProjects/PHPReflectionUtilities"
pathToPhpUnit="$pathToPHPReflectionUtilities/vendor/bin/phpunit"

cd "$pathToPHPReflectionUtilities" || msgAndExit 'PHPReflectionUtilities is not installed'

find \
    "$pathToPHPReflectionUtilities/tests" \
    "$pathToPHPReflectionUtilities/src" \
    -type f -name "*.php" |
    entr -c "$pathToPhpUnit" -c "$pathToPHPReflectionUtilities/php.xml"

