#!/bin/sh
#
# This script will run `phpunit` tests via `entr` whenever
# a file in either PHPUnitTestUtilities's src/ or tests/
# directoy is modified.
#
# Usage:
#
# runPHPUnitTestsOnSavePHPUnitTestUtilities
#

msg() {
    printf '%b%s%b' "\n\n\e[0m\e[105m\e[30m" "$1" "\e[0m\n\n"
}

msgAndExit() {
    msg "$1"
    exit 1
}

pathToPhpProjects="$HOME/Git"
pathToPHPUnitTestUtilities="$pathToPhpProjects/PHPUnitTestUtilities"
pathToPhpUnit="$pathToPHPUnitTestUtilities/vendor/bin/phpunit"

cd "$pathToPHPUnitTestUtilities" || msgAndExit 'PHPUnitTestUtilities is not installed'

find \
    "$pathToPHPUnitTestUtilities/tests" \
    "$pathToPHPUnitTestUtilities/src" \
    -type f -name "*.php" |
    entr -c "$pathToPhpUnit" -c "$pathToPHPUnitTestUtilities/php.xml"

