#!/bin/sh
#
# This script will run `phpunit` tests via `entr` whenever
# a file in either roadyRoutes's src/ or tests/
# directoy is modified.
#
# Usage:
#
# runPHPUnitTestsOnSaveroadyRoutes
#

msg() {
    printf '%b%s%b' "\n\n\e[0m\e[105m\e[30m" "$1" "\e[0m\n\n"
}

msgAndExit() {
    msg "$1"
    exit 1
}

pathToPhpProjects="$HOME/Git"
pathToRoadyRoutes="$pathToPhpProjects/roadyRoutes"
pathToPhpUnit="$pathToRoadyRoutes/vendor/bin/phpunit"

cd "$pathToRoadyRoutes" || msgAndExit 'roadyRoutes is not installed'

find \
    "$pathToRoadyRoutes/tests" \
    "$pathToRoadyRoutes/src" \
    -type f -name "*.php" |
    entr -c "$pathToPhpUnit" -c "$pathToRoadyRoutes/php.xml"

