#!/bin/sh
#
# This script will run `phpunit` tests via `entr` whenever
# a file in either RoadyModuleUtilities's src/ or tests/
# directoy is modified.
#
# Usage:
#
# runPHPUnitTestsOnSaveRoadyModuleUtilities
#

msg() {
    printf '%b%s%b' "\n\n\e[0m\e[105m\e[30m" "$1" "\e[0m\n\n"
}

msgAndExit() {
    msg "$1"
    exit 1
}

pathToPhpProjects="$HOME/Git"
pathToRoadyModuleUtilities="$pathToPhpProjects/RoadyModuleUtilities"
pathToPhpUnit="$pathToRoadyModuleUtilities/vendor/bin/phpunit"

cd "$pathToRoadyModuleUtilities" || msgAndExit 'RoadyModuleUtilities is not installed'

find \
    "$pathToRoadyModuleUtilities/tests" \
    "$pathToRoadyModuleUtilities/src" \
    -type f -name "*.php" |
    entr -c "$pathToPhpUnit" -c "$pathToRoadyModuleUtilities/php.xml"

