#!/bin/sh
#
# This script will run `phpunit` tests via `entr` whenever
# a file in either PHPTextTypes's src/ or tests/
# directoy is modified.
#
# Usage:
#
# runPHPUnitTestsOnSavePHPTextTypes
#

msg() {
    printf '%b%s%b' "\n\n\e[0m\e[105m\e[30m" "$1" "\e[0m\n\n"
}

msgAndExit() {
    msg "$1"
    exit 1
}

pathToPhpProjects="$HOME/Git"
pathToPHPTextTypes="$pathToPhpProjects/PHPTextTypes"
pathToPhpUnit="$pathToPHPTextTypes/vendor/bin/phpunit"

cd "$pathToPHPTextTypes" || msgAndExit 'PHPTextTypes is not installed'

find \
    "$pathToPHPTextTypes/tests" \
    "$pathToPHPTextTypes/src" \
    -type f -name "*.php" |
    entr -c "$pathToPhpUnit" -c "$pathToPHPTextTypes/php.xml"

