#!/bin/sh
#
# This script will run `phpunit` tests via `entr` whenever
# a file in either PHPWebPaths's src/ or tests/
# directoy is modified.
#
# Usage:
#
# runPHPUnitTestsOnSavePHPWebPaths
#

msg() {
    printf '%b%s%b' "\n\n\e[0m\e[105m\e[30m" "$1" "\e[0m\n\n"
}

msgAndExit() {
    msg "$1"
    exit 1
}

pathToPhpProjects="$HOME/Git"
pathToPHPWebPaths="$pathToPhpProjects/PHPWebPaths"
pathToPhpUnit="$pathToPHPWebPaths/vendor/bin/phpunit"

cd "$pathToPHPWebPaths" || msgAndExit 'PHPWebPaths is not installed'

find \
    "$pathToPHPWebPaths/tests" \
    "$pathToPHPWebPaths/src" \
    -type f -name "*.php" |
    entr -c "$pathToPhpUnit" -c "$pathToPHPWebPaths/php.xml"

