#!/bin/sh
#
# This script will run `phpstan` tests via `entr` whenever
# a file in RoadyModuleUtilities's src/ or Tests/ directory
# is modified.
#
# Usage:
#
# runPHPStanTestsOnSavePHPUnitTestUtilties
#

msg() {
    printf '%b%s%b' "\n\n\e[0m\e[105m\e[30m" "$1" "\e[0m\n\n"
}

msgAndExit() {
    msg "$1"
    exit 1
}

pathToPHPProjects="$HOME/Git"
pathToRoadyModuleUtilities="$pathToPHPProjects/RoadyModuleUtilities"
pathToPHPStan="$pathToRoadyModuleUtilities/vendor/bin/phpstan"

cd "$pathToRoadyModuleUtilities" || msgAndExit 'RoadyModuleUtilities is not installed'

find \
    "$pathToRoadyModuleUtilities/tests" \
    "$pathToRoadyModuleUtilities/src" \
    -type f -name "*.php" |
    entr -c "$pathToPHPStan"

