#!/bin/sh
#
# This script will run `phpunit` tests via `entr` whenever
# a file in either PhpUnitTestUtilities's src/ or tests/
# directoy is modified.
#
# Usage:
#
# runPhpUnitTestsOnSavePhpUnitTestUtilities
#

msg() {
    printf '%b%s%b' "\n\n\e[0m\e[105m\e[30m" "$1" "\e[0m\n\n"
}

msgAndExit() {
    msg "$1"
    exit 1
}

pathToPhpProjects="$HOME/Git"
pathToPhpUnitTestUtilities="$pathToPhpProjects/PhpUnitTestUtilities"
pathToPhpUnit="$pathToPhpUnitTestUtilities/vendor/bin/phpunit"

cd "$pathToPhpUnitTestUtilities" || msgAndExit 'PhpUnitTestUtilities is not installed'

find \
    "$pathToPhpUnitTestUtilities/tests" \
    "$pathToPhpUnitTestUtilities/src" \
    -type f -name "*.php" |
    entr -c "$pathToPhpUnit" -c "$pathToPhpUnitTestUtilities/php.xml"

