#!/bin/sh
#
# This script will install and setup composer.
# It is just here for reference.
#
# Whenever you need to re-install composer, visit
# https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md
# to get the most up to date copy of this script, which is provided by
# https://getcomposer.org

EXPECTED_CHECKSUM="$(php -r 'copy("https://composer.github.io/installer.sig", "php://stdout");')"
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
ACTUAL_CHECKSUM="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"

if [ "$EXPECTED_CHECKSUM" != "$ACTUAL_CHECKSUM" ]
then
    >&2 echo 'ERROR: Invalid installer checksum'
    rm composer-setup.php
    exit 1
fi

php composer-setup.php --quiet
RESULT=$?
rm composer-setup.php
exit $RESULT
