#!/bin/sh

msg() {
    printf "\n%b%s%b\n" "\e[0m\e[105m\e[30m" "$1" "\e[0m"
}

msgAndExit() {
    msg "$1"
    exit "$2"
}

[ -z "$1" ] && msgAndExit "Please specify a path to a .php file" 1

[ ! -f "$1" ] &&
    msgAndExit "Please specify a path to an existing .php file" 1

[ ! "php" = "${1##*.}" ] &&
    msgAndExit "Please specify a path to a valid .php file" 1

msg "The following methods are defined by $1"

grep -P "^    (public|private|protected|abstract|final).*function.*$" "$1"
