#!/bin/sh

clear

# Functions

msg() {
    printf '\n\n\e[0m\e[105m\e[30m%s\e[0m\n\n' "$1"
}

msgAndExit() {
    msg "$1"
    exit 1
}

# Variables

#timestamp=$(/usr/bin/date +"%s")
pathToPhpProjects="$HOME/dev/php"
pathToRoady="$pathToPhpProjects/roady"
pathToAppPackager="$pathToRoady/Apps/AppPackager"
pathToAppPackagerPackagedApps="$pathToAppPackager/resources/AppPackages"
pathToRoadyAppPackages="$pathToPhpProjects/roadyAppPackages"
pathToNewAppPackage="$pathToAppPackagerPackagedApps/$1"
pathToAppPackageToUpdate="$pathToRoadyAppPackages/$1"


[ -z ${1+x} ] &&
    msgAndExit "Please specify the name of the App to update."

[ ! -d "$pathToAppPackagerPackagedApps" ] &&
    msgAndExit "There aren't any new App Packages in $pathToAppPackagerPackagedApps. Make sure to create an App Package for the $1 App using the AppPackager App."

[ ! -d "$pathToNewAppPackage" ] &&
    msgAndExit "There isn't an App Package for the $1 App at $pathToNewAppPackage. Make sure to create an App Package for the $1 App using the AppPackager App."

[ ! -d "$pathToRoadyAppPackages" ] && msgAndExit "The roadyAppPackages library must be installed at $pathToRoadyAppPackages"

[ -d "$pathToAppPackageToUpdate" ] && msg "Removing original $pathToAppPackageToUpdate" && rm -Rf "$pathToAppPackageToUpdate"

[ ! -d "$pathToAppPackageToUpdate" ] && msg "Moving $pathToNewAppPackage to $pathToAppPackageToUpdate" && mv "$pathToNewAppPackage" "$pathToAppPackageToUpdate"

cd "$pathToRoadyAppPackages" || msgAndExit "Failed to move into $pathToRoadyAppPackages"

git status

msg "The $1 App was updated successfully, the App Package for the $1 App created by the App Packager at $pathToNewAppPackage has been moved to $pathToAppPackageToUpdate"

