#!/bin/sh

# used the following command to list all installed python packages
# then edited ~/.darling/upgradePythonPackages
#
#    `pip list | awk '{print $1}' | sed 's/-//g' | sed 's/Package//g' > ~/.darling/upgradePythonPackages`
#
# Ideally, refactor to use above command with xargs instead of
# iterating over each installed package listed in this file

/home/darling/.local/bin/pip install beautifulsoup4 --upgrade
/home/darling/.local/bin/pip install blinker --upgrade
/home/darling/.local/bin/pip install Brlapi --upgrade
/home/darling/.local/bin/pip install castero --upgrade
/home/darling/.local/bin/pip install certifi --upgrade
/home/darling/.local/bin/pip install chardet --upgrade
/home/darling/.local/bin/pip install chromegnomeshell --upgrade
/home/darling/.local/bin/pip install CJKwrap --upgrade
/home/darling/.local/bin/pip install click --upgrade
/home/darling/.local/bin/pip install colorama --upgrade
/home/darling/.local/bin/pip install commandnotfound --upgrade
/home/darling/.local/bin/pip install cryptography --upgrade
/home/darling/.local/bin/pip install cupshelpers --upgrade
/home/darling/.local/bin/pip install dbuspython --upgrade
/home/darling/.local/bin/pip install defer --upgrade
/home/darling/.local/bin/pip install distro --upgrade
/home/darling/.local/bin/pip install evdev --upgrade
/home/darling/.local/bin/pip install gevent --upgrade
/home/darling/.local/bin/pip install greenlet --upgrade
/home/darling/.local/bin/pip install grequests --upgrade
/home/darling/.local/bin/pip install hidpidaemon --upgrade
/home/darling/.local/bin/pip install httplib2 --upgrade
/home/darling/.local/bin/pip install idna --upgrade
/home/darling/.local/bin/pip install importlibmetadata --upgrade
/home/darling/.local/bin/pip install jeepney --upgrade
/home/darling/.local/bin/pip install kernelstub --upgrade
/home/darling/.local/bin/pip install keyring --upgrade
/home/darling/.local/bin/pip install languageselector --upgrade
/home/darling/.local/bin/pip install launchpadlib --upgrade
/home/darling/.local/bin/pip install lazr.restfulclient --upgrade
/home/darling/.local/bin/pip install lazr.uri --upgrade
/home/darling/.local/bin/pip install louis --upgrade
/home/darling/.local/bin/pip install lxml --upgrade
/home/darling/.local/bin/pip install macaroonbakery --upgrade
/home/darling/.local/bin/pip install moreitertools --upgrade
/home/darling/.local/bin/pip install msgpack --upgrade
/home/darling/.local/bin/pip install netifaces --upgrade
/home/darling/.local/bin/pip install oauthlib --upgrade
/home/darling/.local/bin/pip install pip --upgrade
/home/darling/.local/bin/pip install poptransition --upgrade
/home/darling/.local/bin/pip install protobuf --upgrade
/home/darling/.local/bin/pip install pycairo --upgrade
/home/darling/.local/bin/pip install pycryptodomex --upgrade
/home/darling/.local/bin/pip install pycups --upgrade
/home/darling/.local/bin/pip install pydbus --upgrade
/home/darling/.local/bin/pip install PyGObject --upgrade
/home/darling/.local/bin/pip install PyJWT --upgrade
/home/darling/.local/bin/pip install pymacaroons --upgrade
/home/darling/.local/bin/pip install PyNaCl --upgrade
/home/darling/.local/bin/pip install pynvim --upgrade
/home/darling/.local/bin/pip install pyparsing --upgrade
/home/darling/.local/bin/pip install pyRFC3339 --upgrade
/home/darling/.local/bin/pip install pythonapt --upgrade
/home/darling/.local/bin/pip install pythondebian --upgrade
/home/darling/.local/bin/pip install pythonmpv --upgrade
/home/darling/.local/bin/pip install pythonvlc --upgrade
/home/darling/.local/bin/pip install pythonxlib --upgrade
/home/darling/.local/bin/pip install pytz --upgrade
/home/darling/.local/bin/pip install pywal --upgrade
/home/darling/.local/bin/pip install pyxattr --upgrade
/home/darling/.local/bin/pip install pyxdg --upgrade
/home/darling/.local/bin/pip install PyYAML --upgrade
/home/darling/.local/bin/pip install repolib --upgrade
/home/darling/.local/bin/pip install repoman --upgrade
/home/darling/.local/bin/pip install requests --upgrade
/home/darling/.local/bin/pip install SecretStorage --upgrade
/home/darling/.local/bin/pip install sessioninstaller --upgrade
/home/darling/.local/bin/pip install setuptools --upgrade
/home/darling/.local/bin/pip install six --upgrade
/home/darling/.local/bin/pip install soupsieve --upgrade
/home/darling/.local/bin/pip install system76driver --upgrade
/home/darling/.local/bin/pip install systemdpython --upgrade
/home/darling/.local/bin/pip install ubuntuadvantagetools --upgrade
/home/darling/.local/bin/pip install ubuntudriverscommon --upgrade
/home/darling/.local/bin/pip install ufw --upgrade
/home/darling/.local/bin/pip install urllib3 --upgrade
/home/darling/.local/bin/pip install wadllib --upgrade
/home/darling/.local/bin/pip install wheel --upgrade
/home/darling/.local/bin/pip install xdg --upgrade
/home/darling/.local/bin/pip install xkit --upgrade
/home/darling/.local/bin/pip install youtubedl --upgrade
/home/darling/.local/bin/pip install zipp --upgrade
/home/darling/.local/bin/pip install zope.event --upgrade
/home/darling/.local/bin/pip install zope.interface --upgrade

