#!/bin/sh

msg() {
    printf '%b%s%b' "\n\n\e[0m\e[105m\e[30m" "$1" "\e[0m\n\n"
}

msgAndExit() {
    msg "$1"
    exit 1
}

mypipePath="${HOME}/DEV/mypipe"

[ ! -p "${mypipePath}" ] && msgAndExit "${mypipePath} does not exist"

clear

msg "--- Output From ${mypipePath} (Use ctrl-c to exit) ---"

while :; do
    cat "${mypipePath}"
    msg "                                        "
done

